controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - swiftpro/joint1
      - swiftpro/joint2
      - swiftpro/joint3
      - swiftpro/joint4
    interface_name: velocity

gpio_controller:
  ros__parameters:
    type: gpio_controllers/GpioCommandController
    gpios:
      - swiftpro/limit_switch
      - swiftpro/pump
    command_interfaces:
      swiftpro/pump:
        - interfaces:
          - pump